import "./globals.css";
import type { Metadata } from "next";
import { fontsClasses } from "@/lib/fonts";

// Components
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/utils/ThemeProvider";

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Main component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontsClasses} antialiased`}>
        <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem>
          <Toaster position="top-right" duration={10000} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
